package com.example.jetpackcompose_crudtodoapp.util

object Constants {
    const val OK = "Ok"
    const val CANCEL = "Cancel"
    const val SELECT = "Select"
    const val PICK_A_DATE = "Pick a date"
    const val EDIT_TODO = "Edit Todo"
    const val NAVIGATE_BACK = "Navigate Back"
    const val SAVE = "Save"
    const val TODO_TITLE = "Todo Title"
    const val TODO_DESCR = "Todo Description"
    const val DESCR = "Description"
    const val SELECT_DUE_DATE = "Select Due Date"
    const val NOT_SELECTED_YET = "Not Selected Yet"
    const val SELECT_CATEGORY = "Select Category"
    const val SELECT_PRIORITY_COLOR = "Select Priority Color"
    const val DUE_DATE = "Due Date"
    const val CATEGORY = "Category"
    const val COLOR = "Color"
    const val DELETE = "Delete"
    const val TODO_DETAILS = "Todo Details"
    const val EMPTY_TITLE = "Title can not be blank."
    const val EMPTY_DUE_DATE = "Due date can not be blank."
    const val EMPTY_CATEGORY = "Category can not be blank."
    const val CATEGORIES = "CATEGORIES"
    const val DELETE_QUESTION = "Are you sure to delete this?"
    const val TASKS = "TASKS"
    const val ADD_NEW_TODO = "Add New Todo"
}
