package com.example.jetpackcompose_crudtodoapp.ui.util

object Constants {
    const val OK = "Ok"
    const val CANCEL = "Cancel"
    const val PICK_A_DATE = "Pick a date"
    const val EDIT_TODO = "Edit Todo"
    const val NAVIGATE_BACK = "Navigate Back"
    const val SAVE = "Save"
    const val TODO_TITLE = "Todo Title"
    const val TODO_DESCR = "Todo Description"
    const val SELECT_DUE_DATE = "Select Due Date"
    const val NOT_SELECTED_YET = "Not Selected Yet"
    const val SELECT_CATEGORY = "Select Category"
    const val SELECT_PRIORITY_COLOR = "Select Priority Color"
    const val DUE_DATE = "Due Date"
    const val CATEGORY = "Category"
    const val COLOR = "Color"
    const val DELETE = "Delete"
    const val TODO_DETAILS = "Todo Details"
    const val EMPTY_TITLE = "Title can not be blank."
    const val EMPTY_DUE_DATE = "Due date can not be blank."
    const val EMPTY_CATEGORY = "Category can not be blank."
    const val CATEGORIES = "CATEGORIES"
    const val DELETE_QUESTION = "Are you sure to delete this?"
    const val TASKS = "TASKS"
    const val ADD_NEW_TODO = "Add New Todo"
    const val ALL = "All"
    const val EMPTY_TODO_LIST = "Empty Task List, Please Add Task"
    const val DATE_FORMAT = "d MMM yyyy"
    const val NOTIFICATION_ID = "notificationId"
    const val NOTIFICATION_INT = 100
    const val NOTIFICATION_TITLE = "TODO ALARM"
    const val NOTIFICATION_TEXT = "You have 1 TODO that needs your attention."
    const val NOTIFICATION_ACTION_TEXT = "Open Nootpad"
    const val CHANNEL_ID = "channel"
    const val CHANNEL_NAME = "backgroundWorkerChannel"
    const val TODO = "TODO"
    const val ADD_ALARM = "Add Alarm"
    const val CLOSE = "Close"
}
